# version: '3.9'
services:
  # db:
  #   image: mysql:8
  #   restart: always
  #   container_name: db

  #   environment:
  #     MYSQL_DATABASE: ${DATABASE_NAME}
  #     # MYSQL_USER: ${DATABASE_USER}
  #     MYSQL_PASSWORD: ${DATABASE_PASSWORD}
  #     MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - ./mysql-data:/var/lib/mysql
  #   networks:
  #     - mynetwork 

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8080"
    restart: always
    container_name: django-app
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports: 
      - "8080:8080"
    # depends_on:
    #   - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # networks:
    #   - mynetwork
    network_mode: "host"
  
  # apache:
  #   build: ./apache
  #   container_name: apache_server_for_ftp
  #   volumes:
  #     - static_volume:/app/static
  #     - media_volume:/app/media
  #   ports:
  #     - "81:80"
  #   networks:
  #     - mynetwork
  #   depends_on:
  #     - web


volumes: 
  static_volume:
  media_volume:

# networks:
#   mynetwork:
#     driver: bridge